### ISSUE TITLE
JesqueDelayedJobThreadService rhows  IllegalFieldValueException

### ISSUE THREAD

**Issue by edwardotis** [Grails-Plugin-Consortium/grails-jesque#25]
The following exception keeps showing up in my logs.

Related Stack and libraries:
grails 3.1.16
java 8
ubuntu 14LTS
compile "org.grails.plugins:jesque:1.2.1"
compile 'joda-time:joda-time:2.8.2'

```
 2017-06-22 22:55:27,065 [ERROR] JesqueDelayedJobThreadService Jesque delayed job exception, attempt 1 of 120
 org.joda.time.IllegalFieldValueException: Value 292278994 for year must be in the range [-292275054,292278993]
 	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)
 	at org.joda.time.chrono.BasicYearDateTimeField.set(BasicYearDateTimeField.java:83)
 	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:129)
 	at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:97)
 	at org.joda.time.DateTime.<init>(DateTime.java:209)
 	at sun.reflect.GeneratedConstructorAccessor122.newInstance(Unknown Source)
 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
 	at grails.plugins.jesque.JesqueDelayedJobService$_nextFireTime_closure3.doCall(JesqueDelayedJobService.groovy:56)
 	at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
 	at grails.plugins.redis.RedisService.withRedis(RedisService.groovy:102)
 	at grails.plugins.redis.RedisService$withRedis.call(Unknown Source)
 	at grails.plugins.jesque.JesqueDelayedJobService.nextFireTime(JesqueDelayedJobService.groovy:50)
 	at grails.plugins.jesque.JesqueDelayedJobService$nextFireTime$0.call(Unknown Source)
 	at grails.plugins.jesque.JesqueDelayedJobThreadService.mainThreadLoop(JesqueDelayedJobThreadService.groovy:48)
 	at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
 	at grails.plugins.jesque.JesqueDelayedJobThreadService$_run_closure1.doCall(JesqueDelayedJobThreadService.groovy:38)
 	at grails.plugins.jesque.JesqueDelayedJobThreadService$_run_closure1.doCall(JesqueDelayedJobThreadService.groovy)
 	at sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
 	at grails.plugins.jesque.JesqueDelayedJobThreadService.withRetryUsingBackoff(JesqueDelayedJobThreadService.groovy:73)
 	at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
 	at grails.plugins.jesque.JesqueDelayedJobThreadService.run(JesqueDelayedJobThreadService.groovy:37)
 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bp-FLN** [comment]
the `JesqueDelayedJobService` has been removed in #27
